#!/bin/bash
# tf_wrapper.sh config
# This file is sourced via the wrapper bash script and therefore should be written in bash
# Tokens of the form %MYVAR% will be replaced with $myvar values defined in the wrapper script

# State file S3 key
backend_key="%STACK%/%ENVIRONMENT%/%LAYER%/terraform.tfstate"

# Plan file name format
plan="%LAYER%-%ENVIRONMENT%-tfplan"

# Set to true to allow the wrapper to update itself
auto_update=false

# Branch from which wrapper updates will  be pulled
update_branch="HEAD"

# Additional arguments to pass to any tflint-ing done by the wrapper
# Note that --recursive is added by default when using -g
lint_args=""
