version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.7.5"
    TERRAFORM_WORKSPACE: "default"
    TERRAFORM_BACKEND_BUCKET: "aws-cloudwan-terraform-state"
    TERRAFORM_BACKEND_KEY: "terraform.tfstate"
    TF_LAYER: "platform"
    TF_ENVIRONMENT: "prd"

phases:
  build:
    commands:
      - bash ./infrastructure/codebuild/scripts/terraform-init.sh

artifacts:
  files:
    - '**/*'